name: release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cli/gh-extension-precompile@v2
        with:
          go_version_file: go.mod
